# Generated by Django 3.1rc1 on 2020-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_name',
            field=models.CharField(default='', max_length=32, verbose_name='Название html-страницы'),
        ),
    ]
