# Generated by Django 3.1rc1 on 2020-08-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_name',
        ),
    ]
