# Generated by Django 3.1 on 2020-08-26 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20200826_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_url',
            field=models.CharField(blank=True, max_length=64, verbose_name='страница в ВК'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 37, 7, 944251)),
        ),
    ]
